#####################################################################
#                                                                   #
# This file is for configuration of the curriculum fetch scripts.   #
#                                                                   #
# Note that correct indentation is critical in YAML files.          #
#                                                                   #
# Be sure to also set environment variables in .env file!           #
#                                                                   #
#####################################################################

fetch_images: true

curriculum_layout:
  repo: shared-curriculum
  directory: lhtp2
  filename: curriculum-layout.yaml

# The defaults are likely fine for everything below this line
docusaurus_docs_dir: 'docs' # relative to project root
docusaurus_static_assets_dir: 'static' # relative to project root
scratch_dir: 'tmp' # relative to project root
images_input_dir: 'images' # folder to find images in within github repos
images_output_dir: 'images' # will go within docusaurus_static_assets_dir
