module.exports = {
  'prework': require('/Users/epicodus/projects/lhtp/docs/prework/sidebar.js'),
  'introduction-to-programming': require('/Users/epicodus/projects/lhtp/docs/introduction-to-programming/sidebar.js'),
  'introduction-to-programming-classic': require('/Users/epicodus/projects/lhtp/docs/introduction-to-programming-classic/sidebar.js'),
  'introduction-to-programming-part-time': require('/Users/epicodus/projects/lhtp/docs/introduction-to-programming-part-time/sidebar.js'),
  'introduction-to-programming-part-time-evening': require('/Users/epicodus/projects/lhtp/docs/introduction-to-programming-part-time-evening/sidebar.js'),
  'intermediate-javascript': require('/Users/epicodus/projects/lhtp/docs/intermediate-javascript/sidebar.js'),
  'intermediate-javascript-classic': require('/Users/epicodus/projects/lhtp/docs/intermediate-javascript-classic/sidebar.js'),
  'intermediate-javascript-part-time': require('/Users/epicodus/projects/lhtp/docs/intermediate-javascript-part-time/sidebar.js'),
  'intermediate-javascript-part-time-evening': require('/Users/epicodus/projects/lhtp/docs/intermediate-javascript-part-time-evening/sidebar.js'),
  'react': require('/Users/epicodus/projects/lhtp/docs/react/sidebar.js'),
  'react-classic': require('/Users/epicodus/projects/lhtp/docs/react-classic/sidebar.js'),
  'react-part-time': require('/Users/epicodus/projects/lhtp/docs/react-part-time/sidebar.js'),
  'react-part-time-evening': require('/Users/epicodus/projects/lhtp/docs/react-part-time-evening/sidebar.js'),
  'c-and-net': require('/Users/epicodus/projects/lhtp/docs/c-and-net/sidebar.js'),
  'c-and-net-classic': require('/Users/epicodus/projects/lhtp/docs/c-and-net-classic/sidebar.js'),
  'c-and-net-part-time': require('/Users/epicodus/projects/lhtp/docs/c-and-net-part-time/sidebar.js'),
  'c-and-net-part-time-evening': require('/Users/epicodus/projects/lhtp/docs/c-and-net-part-time-evening/sidebar.js'),
  'diversity-equity-and-inclusion': require('/Users/epicodus/projects/lhtp/docs/diversity-equity-and-inclusion/sidebar.js'),
  'journaling-curriculum': require('/Users/epicodus/projects/lhtp/docs/journaling-curriculum/sidebar.js'),
  'internship-and-job-search': require('/Users/epicodus/projects/lhtp/docs/internship-and-job-search/sidebar.js'),
  'workshops': require('/Users/epicodus/projects/lhtp/docs/workshops/sidebar.js')
};
