# This is a reusable workflow, called by curriculum repo workflows,
# so context is that of the caller curriculum repo
name: Fetch docs, build, and deploy multiple Docusaurus sites
run-name: Fetch docs, build, and deploy multiple Docusaurus sites

on:
  workflow_call:
    secrets:
      CURRICULUM_ORG:
        required: true
      CURRICULUM_GITHUB_APP_ID:
        required: true
      CURRICULUM_GITHUB_INSTALLATION_ID:
        required: true
      CURRICULUM_GITHUB_APP_PEM:
        required: true
      LHTP_GITHUB_APP_ID:
        required: true
      LHTP_GITHUB_INSTALLATION_ID:
        required: true
      LHTP_GITHUB_APP_PEM:
        required: true

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: epicodus/lhtp

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate Epicodus Curriculum GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: curriculum-app-token
        with:
          app_id: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          installation_id: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Generate Epicodus LHTP GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: lhtp-app-token
        with:
          app_id: ${{ secrets.LHTP_GITHUB_APP_ID }}
          installation_id: ${{ secrets.LHTP_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.LHTP_GITHUB_APP_PEM }}

      - name: Fetch docs
        run: npm run fetch
        env:
          ORG: ${{ secrets.CURRICULUM_ORG }}
          INSTALLATION_TOKEN: ${{ steps.curriculum-app-token.outputs.token }}
          # APP_ID: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          # INSTALLATION_ID: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          # PRIVATE_KEY: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

  build:
    needs: fetch-data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        track: ['ft', 'ft-old', 'pt', 'pt-evening']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build ${{ matrix.track }}
        run: cd ${{ matrix.track }} && npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.track }}
          path: ./build/${{ matrix.track }}

  deploy-temp:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download all build artifacts
      uses: actions/download-artifact@v2
      with:
        path: ./all-builds

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ steps.lhtp-app-token.outputs.token }}
        publish_branch: gh-pages
        publish_dir: ./all-builds
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_message: 'Deploy to gh-pages'

  trigger-deploy-full-time:
    needs: deploy-temp
    uses: epicodus/lhtp-full-time/.github/workflows/deploy.yml@main

  trigger-deploy-full-time-classic:
    needs: deploy-temp
    uses: epicodus/lhtp-full-time-old/.github/workflows/deploy.yml@main

  trigger-deploy-part-time:
    needs: deploy-temp
    uses: epicodus/lhtp-part-time/.github/workflows/deploy.yml@main

  trigger-deploy-part-time-evening:
    needs: deploy-temp
    uses: epicodus/lhtp-part-time-evening/.github/workflows/deploy.yml@main
