# this workflow is triggered manually, so the context is the repo from which it is run
name: Fetch docs, build, and deploy Docusaurus site (manually triggered)
run-name: Fetch docs, build, and deploy Docusaurus site (manually triggered)

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Fetch docs
        run: npm run fetch
        env:
          ORG: ${{ secrets.CURRICULUM_ORG }}
          APP_ID: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          INSTALLATION_ID: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          PRIVATE_KEY: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: 'Deploy to GitHub Pages'
