# this workflow is triggered manually, so the context is the repo from which it is run
name: Manual Trigger - Fetch docs, build, and deploy multiple Docusaurus sites

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate Epicodus Curriculum GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: curriculum-app-token
        with:
          app_id: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          installation_id: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Fetch docs and create docusaurus source directories for each track
        run: npm run fetch
        env:
          ORG: ${{ secrets.CURRICULUM_ORG }}
          INSTALLATION_TOKEN: ${{ steps.curriculum-app-token.outputs.token }}
          # APP_ID: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          # INSTALLATION_ID: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          # PRIVATE_KEY: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Upload fetched data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: fetched-data
          path: ./tracks

  build:
    needs: fetch-data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        track: ['pre-work', 'dei', 'career-services', 'workshops', 'full-time', 'part-time', 'full-time-pre-october', 'part-time-evening']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Download fetched data artifact
        uses: actions/download-artifact@v3
        with:
          name: fetched-data
          path: ./tracks

      - name: Build ${{ matrix.track }}
        run: cd ./tracks/${{ matrix.track }} && npm run build

      - name: Create CNAME
        run: echo "${{ matrix.track }}.learnhowtoprogram.com" > ./tracks/${{ matrix.track }}/CNAME

      - name: Clone target repo
        run: git clone https://github.com/epicodus/lhtp-${{ matrix.track }}.git ./target-repo

      - name: Switch to gh-pages branch
        run: |
          cd ./target-repo
          git checkout gh-pages

      - name: Remove existing files
        run: |
          cd ./target-repo
          rm -rf *

      - name: Copy build to target repo
        run: mv ./tracks/${{ matrix.track }}/* ./target-repo

      - name: Generate Epicodus LHTP GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: lhtp-app-token
        with:
          app_id: ${{ secrets.LHTP_GITHUB_APP_ID }}
          installation_id: ${{ secrets.LHTP_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.LHTP_GITHUB_APP_PEM }}

      - name: Push to target repo
        run: |
          cd ./target-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to gh-pages" || echo "No changes to commit"
          git push --force https://${{ steps.lhtp-app-token.outputs.app_token }}@github.com/epicodus/lhtp-${{ matrix.track }}.git
