# This is a reusable workflow, called by curriculum repo workflows,
# so context is that of the caller curriculum repo
name: Fetch docs, build, and deploy Docusaurus site
run-name: Fetch docs, build, and deploy Docusaurus site

on:
  # Allows this workflow to be triggered by another workflow
  workflow_call:
    secrets:
      CURRICULUM_ORG:
        required: true
      CURRICULUM_GITHUB_APP_ID:
        required: true
      CURRICULUM_GITHUB_INSTALLATION_ID:
        required: true
      CURRICULUM_GITHUB_APP_PEM:
        required: true
      LHTP_GITHUB_APP_ID:
        required: true
      LHTP_GITHUB_INSTALLATION_ID:
        required: true
      LHTP_GITHUB_APP_PEM:
        required: true

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: epicodus/lhtp

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate Epicodus Curriculum GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: curriculum-app-token
        with:
          app_id: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          installation_id: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Generate Epicodus LHTP GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: lhtp-app-token
        with:
          app_id: ${{ secrets.LHTP_GITHUB_APP_ID }}
          installation_id: ${{ secrets.LHTP_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.LHTP_GITHUB_APP_PEM }}

      - name: Fetch docs
        run: npm run fetch
        env:
          ORG: ${{ secrets.CURRICULUM_ORG }}
          APP_ID: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          INSTALLATION_ID: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          PRIVATE_KEY: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}
          # CURRICULUM_GITHUB_APP_TOKEN: ${{ steps.curriculum-app-token.outputs.token }}

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ steps.lhtp-app-token.outputs.token }}
          external_repository: epicodus/lhtp
          publish_branch: gh-pages
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: 'Deploy to GitHub Pages'
