name: Fetch docs, build, and deploy Docusaurus site
run-name: Fetch docs, build, and deploy Docusaurus site

on:
  # Allows this workflow to be triggered by another workflow
  workflow_call:
    secrets:
      CURRICULUM_ORG:
        required: true
      CURRICULUM_GITHUB_APP_ID:
        required: true
      CURRICULUM_GITHUB_INSTALLATION_ID:
        required: true
      CURRICULUM_GITHUB_APP_PEM:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'epicodus/lhtp'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Fetch docs
        run: npm run fetch
        env:
          ORG: ${{ secrets.CURRICULUM_ORG }}
          APP_ID: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          INSTALLATION_ID: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          PRIVATE_KEY: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: 'Deploy to GitHub Pages'
