# this workflow is triggered manually, so the context is the repo from which it is run
name: Manual Trigger - Fetch docs, build, and deploy multiple Docusaurus sites

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate Epicodus Curriculum GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: curriculum-app-token
        with:
          app_id: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          installation_id: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Generate Epicodus LHTP GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: lhtp-app-token
        with:
          app_id: ${{ secrets.LHTP_GITHUB_APP_ID }}
          installation_id: ${{ secrets.LHTP_GITHUB_INSTALLATION_ID }}
          private_key: ${{ secrets.LHTP_GITHUB_APP_PEM }}

      - name: Fetch docs and create docusaurus source directories for each track
        run: npm run fetch fidgetech
        env:
          ORG: ${{ secrets.CURRICULUM_ORG }}
          INSTALLATION_TOKEN: ${{ steps.curriculum-app-token.outputs.token }}
          # APP_ID: ${{ secrets.CURRICULUM_GITHUB_APP_ID }}
          # INSTALLATION_ID: ${{ secrets.CURRICULUM_GITHUB_INSTALLATION_ID }}
          # PRIVATE_KEY: ${{ secrets.CURRICULUM_GITHUB_APP_PEM }}

      - name: Build fidgetech
        run: cd ./tracks/fidgetech && npm run build

      - name: Deploy fidgetech to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ steps.lhtp-app-token.outputs.token }}
          external_repository: epicodus/lhtp-fidgetech
          publish_branch: gh-pages
          publish_dir: ./tracks/fidgetech/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: 'Deploy fidgetech to GitHub Pages'
